// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

namespace LT.DigitalOffice.ProjectService.Database.Migrations
{
    [DbContext(typeof(ProjectServiceDbContext))]
    partial class ProjectServiceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProjectService.Database.Entities.DbProject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Deferred")
                        .HasColumnType("bit");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("ProjectService.Database.Entities.DbProjectFile", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ProjectId", "FileId");

                    b.ToTable("DbProjectFile");
                });

            modelBuilder.Entity("ProjectService.Database.Entities.DbProjectManagerUser", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ManagerUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ProjectId", "ManagerUserId");

                    b.ToTable("DbProjectManagerUser");
                });

            modelBuilder.Entity("ProjectService.Database.Entities.DbProjectWorkerUser", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WorkerUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ProjectId", "WorkerUserId");

                    b.ToTable("DbProjectWorkerUser");
                });

            modelBuilder.Entity("ProjectService.Database.Entities.DbProjectFile", b =>
                {
                    b.HasOne("ProjectService.Database.Entities.DbProject", "Project")
                        .WithMany("FilesIds")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectService.Database.Entities.DbProjectManagerUser", b =>
                {
                    b.HasOne("ProjectService.Database.Entities.DbProject", "Project")
                        .WithMany("ManagersUsersIds")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectService.Database.Entities.DbProjectWorkerUser", b =>
                {
                    b.HasOne("ProjectService.Database.Entities.DbProject", "Project")
                        .WithMany("WorkersUsersIds")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
