name: .NET Core

on:
  push:
    branches: 
      - develop
      - feature/*
  pull_request:
    branches: [ develop, master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1

    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore ./digitaloffice/
    - name: Build
      run: dotnet build ./digitaloffice/ --configuration Release --no-restore
    - name: Test
      run: dotnet test ./digitaloffice/ --no-restore --verbosity normal
