name: Test Docker

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore ./DigitalOffice/LT.DigitalOffice.sln
    - name: Build
      run: dotnet build ./DigitalOffice/LT.DigitalOffice.sln --no-restore
    - name: Test
      run: dotnet test ./DigitalOffice/LT.DigitalOffice.sln --no-restore --verbosity normal

    - name: Build and push Docker images
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_LOGIN }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: services
